name: Build and Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build App (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm run build:linux
      
    - name: Build App (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run build:win

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gphotos-uploader-${{ matrix.os }}
        path: |
          dist/*.exe
          dist/*.AppImage

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-files
          merge-multiple: true
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-files/*.exe
            dist-files/*.AppImage
          generate_release_notes: true